default:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: aec-students
      schema: dbt_amirazouaghi
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
  target: dev